### ISSUE TITLE
Question about partial support

### ISSUE THREAD

**Issue by alebelcor** [anandthakker/doiuse#15]
Very cool project. I have a quick question.

It says right there in the README that `box-sizing` isn't supported by IE8+ and I believe that's not entirely accurate.

If we check the caniuse db we'll see that IE8+ has partial support, meaning that they do support `box-sizing` but only when the values `content-box` (the default) and `border-box` are used.

Is the tool considering partial support when it makes a decision about a warning?

Thanks!

**Comment by anandthakker** [comment]
Hi @alebelcor -- yeah, so this is a bug/limitation with the current tool: it just warns about any feature that doesn't have a `'y'` (full support) for the selected browsers.  Definitely something that should be improved, and related to #13, I think.

**Comment by maddesigns** [comment]
had a similar issue with rem unit 
`rem (root em) units not supported by: IE (9,10) (rem)` 

would be great if there were a differentiation between *not supported* and *partial support*

**Comment by svistunov** [comment]
:+1:

**Comment by StefanSchwartze** [comment]
I am very interested in this feature because I have to be able to differentiate between completely unsupported and only partially supported features; I am working currently on this feature, but before sending a PR, what do you think about the approach to just add an additional property e.g. "partial"? The message output from postcss would still be a one-liner, separating between partially and not supported browsers..

**Comment by anandthakker** [comment]
@StefanSchwartze Sounds like a good approach to me -- would be happy to accept a PR for this!

**Comment by StefanSchwartze** [comment]
https://github.com/anandthakker/doiuse/pull/47

**Comment by StefanSchwartze** [comment]
Closed with https://github.com/anandthakker/doiuse/pull/47 :)
