### ISSUE TITLE
Feature: .doiuserc config file

### ISSUE THREAD

**Issue by marcobiedermann** [anandthakker/doiuse#50]
It would be great, if you could add a `.doiuserc` config file to your projects in which all options are set.

**Comment by LJNielsenDk** [comment]
Using the config file and/or package.json methods of configuring https://github.com/ai/browserslist might be a better idea.

**Comment by stevewillard** [comment]
Using the browserlist config file has already been added/merged, but a release for it was never made 😢 
#62

**Comment by anandthakker** [comment]
☝️ Just published in 2.6.0 -- sorry for the delay!

**Comment by thany** [comment]
If I leave out the config object, since `browsers` was the only remaining option for me, I get this:
```
TypeError: Cannot read property 'browsers' of undefined
```
I can't help but assume `browsers` is the only option for a lot of folks. Leaving out the options alltogether seems the conventional thing to do if it would otherwise be a simple `{ }`, but alas, it produces the above error.

**Comment by ismay** [comment]
A pr allowing users to omit the options object altogether would be welcome. Other than that, this has been resolved with 2.6.0. If not feel free to let us know!

**Comment by niftylettuce** [comment]
This needs to be re-opened.  You should not get an error out of the box if you don't specify a `browsers` option.  Related to <https://github.com/anandthakker/doiuse/issues/63#issuecomment-368350669>
